services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodets-sap-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - mssql_network

networks:
  mssql_network:
    external: true
